image: pyguerder/bitbucket-pipelines-php73

pipelines:
  default:
    - step:
        name: unit test
        caches:
          - composer
          - vendor-directory
        script:
          - apt-get update && apt-get install -y git openssh-server
          - composer install --no-interaction --no-progress --prefer-dist --ignore-platform-reqs
          - ./vendor/bin/phpunit --testsuite "Unit Test Suite"

definitions:
  caches:
    vendor-directory: vendor
